# AUTO-GENERATED by scripts/gen-errors.py — DO NOT EDIT DIRECTLY
# Source: spec/errors.yaml (version 1)
# Run: python scripts/gen-errors.py

from __future__ import annotations
from typing import Literal, Optional

ArchonBucket = Literal['rate_limit', 'auth', 'model_access', 'crash', 'unknown']

class GeminiError(Exception):
    bucket: ArchonBucket = 'unknown'
    retryable: bool = False
    retry_after_ms: Optional[int] = None

    def __init__(
        self,
        message: str = 'Gemini CLI error: {message}',
        *,
        retry_after_ms: Optional[int] = None,
    ) -> None:
        super().__init__(message)
        if retry_after_ms is not None:
            self.retry_after_ms = retry_after_ms


class RateLimitError(GeminiError):
    bucket: ArchonBucket = 'rate_limit'
    retryable: bool = True
    retry_after_ms: Optional[int] = None

    def __init__(
        self,
        message: str = '',
        *,
        retry_after_ms: Optional[int] = None,
    ) -> None:
        super().__init__(message)
        if retry_after_ms is not None:
            self.retry_after_ms = retry_after_ms


class AuthError(GeminiError):
    bucket: ArchonBucket = 'auth'
    retryable: bool = False
    retry_after_ms: Optional[int] = None

    def __init__(
        self,
        message: str = '',
        *,
        retry_after_ms: Optional[int] = None,
    ) -> None:
        super().__init__(message)
        if retry_after_ms is not None:
            self.retry_after_ms = retry_after_ms


class NotConfigured(AuthError):
    bucket: ArchonBucket = 'auth'
    retryable: bool = False
    retry_after_ms: Optional[int] = None

    def __init__(
        self,
        message: str = '',
        *,
        retry_after_ms: Optional[int] = None,
    ) -> None:
        super().__init__(message)
        if retry_after_ms is not None:
            self.retry_after_ms = retry_after_ms


class Forbidden403(AuthError):
    bucket: ArchonBucket = 'auth'
    retryable: bool = False
    retry_after_ms: Optional[int] = None

    def __init__(
        self,
        message: str = '',
        *,
        retry_after_ms: Optional[int] = None,
    ) -> None:
        super().__init__(message)
        if retry_after_ms is not None:
            self.retry_after_ms = retry_after_ms


class Expired(AuthError):
    bucket: ArchonBucket = 'auth'
    retryable: bool = False
    retry_after_ms: Optional[int] = None

    def __init__(
        self,
        message: str = '',
        *,
        retry_after_ms: Optional[int] = None,
    ) -> None:
        super().__init__(message)
        if retry_after_ms is not None:
            self.retry_after_ms = retry_after_ms


class ToSViolation(AuthError):
    bucket: ArchonBucket = 'auth'
    retryable: bool = False
    retry_after_ms: Optional[int] = None

    def __init__(
        self,
        message: str = '',
        *,
        retry_after_ms: Optional[int] = None,
    ) -> None:
        super().__init__(message)
        if retry_after_ms is not None:
            self.retry_after_ms = retry_after_ms


class ModelAccessError(GeminiError):
    bucket: ArchonBucket = 'model_access'
    retryable: bool = False
    retry_after_ms: Optional[int] = None

    def __init__(
        self,
        message: str = '',
        *,
        retry_after_ms: Optional[int] = None,
    ) -> None:
        super().__init__(message)
        if retry_after_ms is not None:
            self.retry_after_ms = retry_after_ms


class InvalidPromptError(GeminiError):
    bucket: ArchonBucket = 'unknown'
    retryable: bool = False
    retry_after_ms: Optional[int] = None

    def __init__(
        self,
        message: str = '',
        *,
        retry_after_ms: Optional[int] = None,
    ) -> None:
        super().__init__(message)
        if retry_after_ms is not None:
            self.retry_after_ms = retry_after_ms


class ProcessError(GeminiError):
    bucket: ArchonBucket = 'crash'
    retryable: bool = False
    retry_after_ms: Optional[int] = None

    def __init__(
        self,
        message: str = '',
        *,
        retry_after_ms: Optional[int] = None,
    ) -> None:
        super().__init__(message)
        if retry_after_ms is not None:
            self.retry_after_ms = retry_after_ms


class ProcessCrashError(ProcessError):
    bucket: ArchonBucket = 'crash'
    retryable: bool = False
    retry_after_ms: Optional[int] = None

    def __init__(
        self,
        message: str = '',
        *,
        retry_after_ms: Optional[int] = None,
    ) -> None:
        super().__init__(message)
        if retry_after_ms is not None:
            self.retry_after_ms = retry_after_ms


class AbortError(ProcessError):
    bucket: ArchonBucket = 'crash'
    retryable: bool = False
    retry_after_ms: Optional[int] = None

    def __init__(
        self,
        message: str = 'Query aborted by caller',
        *,
        retry_after_ms: Optional[int] = None,
    ) -> None:
        super().__init__(message)
        if retry_after_ms is not None:
            self.retry_after_ms = retry_after_ms


class ParseError(GeminiError):
    bucket: ArchonBucket = 'unknown'
    retryable: bool = False
    retry_after_ms: Optional[int] = None

    def __init__(
        self,
        message: str = '',
        *,
        retry_after_ms: Optional[int] = None,
    ) -> None:
        super().__init__(message)
        if retry_after_ms is not None:
            self.retry_after_ms = retry_after_ms


class UnsupportedFeatureError(GeminiError):
    bucket: ArchonBucket = 'unknown'
    retryable: bool = False
    retry_after_ms: Optional[int] = None

    def __init__(
        self,
        message: str = '',
        *,
        retry_after_ms: Optional[int] = None,
    ) -> None:
        super().__init__(message)
        if retry_after_ms is not None:
            self.retry_after_ms = retry_after_ms


class GeminiNotFoundError(GeminiError):
    bucket: ArchonBucket = 'unknown'
    retryable: bool = False
    retry_after_ms: Optional[int] = None

    def __init__(
        self,
        message: str = 'gemini-cli not found. Install with: npm install -g @google/gemini-cli',
        *,
        retry_after_ms: Optional[int] = None,
    ) -> None:
        super().__init__(message)
        if retry_after_ms is not None:
            self.retry_after_ms = retry_after_ms


