#!/usr/bin/env python3
# scripts/gen-errors.py
# Reads spec/errors.yaml, writes python/src/gemini_sdk/errors/errors.py.
# Naming: YAML retry_after_ms_source -> Python retry_after_ms (snake_case, PEP-8).
# Run: python scripts/gen-errors.py

from __future__ import annotations

import pathlib

import yaml

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
YAML_PATH = REPO_ROOT / "spec" / "errors.yaml"
OUT_PATH = REPO_ROOT / "python" / "src" / "gemini_sdk" / "errors" / "errors.py"

doc = yaml.safe_load(YAML_PATH.read_text(encoding="utf-8"))

header = (
    f"# AUTO-GENERATED by scripts/gen-errors.py \u2014 DO NOT EDIT DIRECTLY\n"
    f"# Source: spec/errors.yaml (version {doc['version']})\n"
    f"# Run: python scripts/gen-errors.py\n\n"
    "from __future__ import annotations\n"
    "from typing import Literal, Optional\n\n"
)
out = header

# Emit ArchonBucket type alias
buckets = ", ".join(f"'{b}'" for b in doc["buckets"])
out += f"ArchonBucket = Literal[{buckets}]\n\n"

for entry in doc["errors"]:
    base = "Exception" if entry["base"] == "Error" else entry["base"]
    msg_template = entry.get("message_template", "")
    default_msg = repr(msg_template)
    retryable = "True" if entry.get("retryable") else "False"
    bucket = repr(entry["bucket"])

    out += f"class {entry['name']}({base}):\n"
    out += f"    bucket: ArchonBucket = {bucket}\n"
    out += f"    retryable: bool = {retryable}\n"
    out += f"    retry_after_ms: Optional[int] = None\n\n"
    out += (
        f"    def __init__(\n"
        f"        self,\n"
        f"        message: str = {default_msg},\n"
        f"        *,\n"
        f"        retry_after_ms: Optional[int] = None,\n"
        f"    ) -> None:\n"
    )
    out += f"        super().__init__(message)\n"
    out += f"        if retry_after_ms is not None:\n"
    out += f"            self.retry_after_ms = retry_after_ms\n"
    out += "\n\n"

OUT_PATH.write_text(out, encoding="utf-8")
print(f"Wrote {OUT_PATH} ({len(doc['errors'])} classes)")
