#!/usr/bin/env node
// scripts/gen-errors.mjs
// Reads spec/errors.yaml, writes ts/src/errors/errors.ts.
// Naming: YAML retry_after_ms_source → TS retryAfterMs.
// Run: node scripts/gen-errors.mjs

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import yaml from 'js-yaml';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');
const YAML_PATH = resolve(REPO_ROOT, 'spec/errors.yaml');
const OUT_PATH = resolve(REPO_ROOT, 'ts/src/errors/errors.ts');

const doc = yaml.load(readFileSync(YAML_PATH, 'utf8'));

const HEADER =
  `// AUTO-GENERATED by scripts/gen-errors.mjs — DO NOT EDIT DIRECTLY\n` +
  `// Source: spec/errors.yaml (version ${doc.version})\n` +
  `// Run: node scripts/gen-errors.mjs\n\n`;

let out = HEADER;

// Emit ArchonBucket type
out += `export type ArchonBucket = ${doc.buckets.map((b) => `'${b}'`).join(' | ')};\n\n`;

// Track which classes have been emitted so subclasses can skip inherited fields
const emittedClasses = new Set();

for (const entry of doc.errors) {
  const baseClass = entry.base === 'Error' ? 'Error' : entry.base;
  const defaultMsg = entry.message_template
    ? JSON.stringify(entry.message_template)
    : `''`;
  const retryableLiteral = entry.retryable ? 'true' : 'false';
  const bucket = `'${entry.bucket}'`;

  // Only redeclare retryAfterMs on the root class (GeminiError).
  // Subclasses inherit it; redeclaring causes TS2612 on strict targets.
  const isRoot = entry.base === 'Error';
  // Only redeclare bucket/retryable on subclasses if value differs from base
  // (always emit to keep generated file fully self-describing, but only
  // declare retryAfterMs on root).

  out += `export class ${entry.name} extends ${baseClass} {\n`;
  out += `  readonly bucket: ArchonBucket = ${bucket};\n`;
  out += `  readonly retryable: boolean = ${retryableLiteral};\n`;
  if (isRoot) {
    out += `  retryAfterMs?: number;\n\n`;
  } else {
    out += `\n`;
  }
  out += `  constructor(message?: string, options?: { retryAfterMs?: number }) {\n`;
  if (isRoot) {
    out += `    super(message ?? ${defaultMsg});\n`;
    out += `    this.name = '${entry.name}';\n`;
    out += `    Object.setPrototypeOf(this, new.target.prototype);\n`;
    out += `    if (options?.retryAfterMs !== undefined) this.retryAfterMs = options.retryAfterMs;\n`;
  } else {
    out += `    super(message ?? ${defaultMsg}, options);\n`;
    out += `    this.name = '${entry.name}';\n`;
    out += `    Object.setPrototypeOf(this, new.target.prototype);\n`;
  }
  out += `  }\n`;
  out += `}\n\n`;

  emittedClasses.add(entry.name);
}

writeFileSync(OUT_PATH, out, 'utf8');
console.log(`Wrote ${OUT_PATH} (${doc.errors.length} classes)`);
