#!/usr/bin/env bash
# mirror-changelog.sh — REL-04
#
# Copies the top version section from root CHANGELOG.md (generated by
# changesets for @gemini-sdk/core) into python/CHANGELOG.md so the Python
# package release notes stay in sync with the TS changelog.
#
# Usage: bash scripts/mirror-changelog.sh
# Prerequisites: CHANGELOG.md and python/CHANGELOG.md exist.
# Exit codes: 0 on success, 1 on missing file, 2 on parse failure.

set -euo pipefail

ROOT_CHANGELOG="CHANGELOG.md"
PY_CHANGELOG="python/CHANGELOG.md"

if [ ! -f "$ROOT_CHANGELOG" ]; then
  echo "ERROR: $ROOT_CHANGELOG not found" >&2
  exit 1
fi
if [ ! -f "$PY_CHANGELOG" ]; then
  echo "ERROR: $PY_CHANGELOG not found" >&2
  exit 1
fi

# Extract everything from the first "## " line up to (but not including) the second "## " line.
TOP_SECTION=$(awk '
  /^## / { count++; if (count == 2) exit }
  count >= 1 { print }
' "$ROOT_CHANGELOG")

if [ -z "$TOP_SECTION" ]; then
  echo "ERROR: no version section found in $ROOT_CHANGELOG" >&2
  exit 2
fi

# Strip any existing top "## " section from python/CHANGELOG.md and prepend the new one.
# Preserve the "# gemini-sdk (Python)" header (line 1).
HEADER=$(head -n 1 "$PY_CHANGELOG")
REMAINDER=$(awk '
  BEGIN { skip = 0; count = 0 }
  NR == 1 { next }  # skip header (already captured)
  /^## / { count++; if (count == 1) { skip = 1; next } }
  /^## / && count >= 2 { skip = 0 }
  skip == 0 && NR > 1 { print }
' "$PY_CHANGELOG")

{
  echo "$HEADER"
  echo ""
  echo "$TOP_SECTION"
  if [ -n "$REMAINDER" ]; then
    echo "$REMAINDER"
  fi
} > "$PY_CHANGELOG.tmp"

mv "$PY_CHANGELOG.tmp" "$PY_CHANGELOG"
echo "Mirrored top section from $ROOT_CHANGELOG to $PY_CHANGELOG"
