// AUTO-GENERATED by scripts/gen-errors.mjs — DO NOT EDIT DIRECTLY
// Source: spec/errors.yaml (version 1)
// Run: node scripts/gen-errors.mjs

export type ArchonBucket = 'rate_limit' | 'auth' | 'model_access' | 'crash' | 'unknown';

export class GeminiError extends Error {
  readonly bucket: ArchonBucket = 'unknown';
  readonly retryable: boolean = false;
  retryAfterMs?: number;

  constructor(message?: string, options?: { retryAfterMs?: number }) {
    super(message ?? "Gemini CLI error: {message}");
    this.name = 'GeminiError';
    Object.setPrototypeOf(this, new.target.prototype);
    if (options?.retryAfterMs !== undefined) this.retryAfterMs = options.retryAfterMs;
  }
}

export class RateLimitError extends GeminiError {
  readonly bucket: ArchonBucket = 'rate_limit';
  readonly retryable: boolean = true;

  constructor(message?: string, options?: { retryAfterMs?: number }) {
    super(message ?? '', options);
    this.name = 'RateLimitError';
    Object.setPrototypeOf(this, new.target.prototype);
  }
}

export class AuthError extends GeminiError {
  readonly bucket: ArchonBucket = 'auth';
  readonly retryable: boolean = false;

  constructor(message?: string, options?: { retryAfterMs?: number }) {
    super(message ?? '', options);
    this.name = 'AuthError';
    Object.setPrototypeOf(this, new.target.prototype);
  }
}

export class NotConfigured extends AuthError {
  readonly bucket: ArchonBucket = 'auth';
  readonly retryable: boolean = false;

  constructor(message?: string, options?: { retryAfterMs?: number }) {
    super(message ?? '', options);
    this.name = 'NotConfigured';
    Object.setPrototypeOf(this, new.target.prototype);
  }
}

export class Forbidden403 extends AuthError {
  readonly bucket: ArchonBucket = 'auth';
  readonly retryable: boolean = false;

  constructor(message?: string, options?: { retryAfterMs?: number }) {
    super(message ?? '', options);
    this.name = 'Forbidden403';
    Object.setPrototypeOf(this, new.target.prototype);
  }
}

export class Expired extends AuthError {
  readonly bucket: ArchonBucket = 'auth';
  readonly retryable: boolean = false;

  constructor(message?: string, options?: { retryAfterMs?: number }) {
    super(message ?? '', options);
    this.name = 'Expired';
    Object.setPrototypeOf(this, new.target.prototype);
  }
}

export class ToSViolation extends AuthError {
  readonly bucket: ArchonBucket = 'auth';
  readonly retryable: boolean = false;

  constructor(message?: string, options?: { retryAfterMs?: number }) {
    super(message ?? '', options);
    this.name = 'ToSViolation';
    Object.setPrototypeOf(this, new.target.prototype);
  }
}

export class ModelAccessError extends GeminiError {
  readonly bucket: ArchonBucket = 'model_access';
  readonly retryable: boolean = false;

  constructor(message?: string, options?: { retryAfterMs?: number }) {
    super(message ?? '', options);
    this.name = 'ModelAccessError';
    Object.setPrototypeOf(this, new.target.prototype);
  }
}

export class InvalidPromptError extends GeminiError {
  readonly bucket: ArchonBucket = 'unknown';
  readonly retryable: boolean = false;

  constructor(message?: string, options?: { retryAfterMs?: number }) {
    super(message ?? '', options);
    this.name = 'InvalidPromptError';
    Object.setPrototypeOf(this, new.target.prototype);
  }
}

export class ProcessError extends GeminiError {
  readonly bucket: ArchonBucket = 'crash';
  readonly retryable: boolean = false;

  constructor(message?: string, options?: { retryAfterMs?: number }) {
    super(message ?? '', options);
    this.name = 'ProcessError';
    Object.setPrototypeOf(this, new.target.prototype);
  }
}

export class ProcessCrashError extends ProcessError {
  readonly bucket: ArchonBucket = 'crash';
  readonly retryable: boolean = false;

  constructor(message?: string, options?: { retryAfterMs?: number }) {
    super(message ?? '', options);
    this.name = 'ProcessCrashError';
    Object.setPrototypeOf(this, new.target.prototype);
  }
}

export class AbortError extends ProcessError {
  readonly bucket: ArchonBucket = 'crash';
  readonly retryable: boolean = false;

  constructor(message?: string, options?: { retryAfterMs?: number }) {
    super(message ?? "Query aborted by caller", options);
    this.name = 'AbortError';
    Object.setPrototypeOf(this, new.target.prototype);
  }
}

export class ParseError extends GeminiError {
  readonly bucket: ArchonBucket = 'unknown';
  readonly retryable: boolean = false;

  constructor(message?: string, options?: { retryAfterMs?: number }) {
    super(message ?? '', options);
    this.name = 'ParseError';
    Object.setPrototypeOf(this, new.target.prototype);
  }
}

export class UnsupportedFeatureError extends GeminiError {
  readonly bucket: ArchonBucket = 'unknown';
  readonly retryable: boolean = false;

  constructor(message?: string, options?: { retryAfterMs?: number }) {
    super(message ?? '', options);
    this.name = 'UnsupportedFeatureError';
    Object.setPrototypeOf(this, new.target.prototype);
  }
}

export class GeminiNotFoundError extends GeminiError {
  readonly bucket: ArchonBucket = 'unknown';
  readonly retryable: boolean = false;

  constructor(message?: string, options?: { retryAfterMs?: number }) {
    super(message ?? "gemini-cli not found. Install with: npm install -g @google/gemini-cli", options);
    this.name = 'GeminiNotFoundError';
    Object.setPrototypeOf(this, new.target.prototype);
  }
}

